# -- Site Configuration --
# https://github.com/ldm0715/xuanzhi

baseURL = 'https://ernsky.github.io/'
title = 'Ernsky'
theme = 'xuanzhi'
defaultContentLanguage = 'zh-cn'

enableRobotsTXT = true
enableEmoji = true

[markup]
  [markup.highlight]
    style = 'monokailight'
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.goldmark.parser]
    attribute.block = true
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      inline = [['\(', '\)']]
      block = [['\[', '\]'], ['$$', '$$']]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  accent = 'terracotta'
  author = 'Ernsky'
  description = '记录随笔与技术，一建备考中'
  mainSections = ['posts']
  [params.hero]
    greeting = '一纸短笺，见字如面'
